services:
  - type: web
    name: smc-academy-react
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
